#!/usr/bin/env python3
"""
Advanced PyInstaller configuration generator for NEL Demo.
This script generates a .spec file with optimized settings for building standalone executables.
"""

import sys
from pathlib import Path

def generate_spec_file(project_root: Path, use_upx: bool = False):
    """Generate PyInstaller spec file with advanced configuration."""
    
    spec_content = f'''# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for NEL Demo
Generated by build_config.py
"""

import sys
from pathlib import Path

# Project paths
project_root = Path(r'{project_root}')
src_dir = project_root / 'src'
models_dir = project_root / 'models'
inputs_dir = project_root / 'inputs'
data_dir = project_root / 'data'

block_cipher = None

# Analysis - specify all dependencies and data files
a = Analysis(
    [str(src_dir / 'gui.py')],
    pathex=[str(project_root)],
    binaries=[],
    datas=[
        (str(models_dir), 'models'),
        (str(inputs_dir), 'inputs'),
        (str(data_dir), 'data'),
    ],
    hiddenimports=[
        'spacy',
        'cyrtranslit',
        'tkinter',
        'tkinter.ttk',
        'tkinter.scrolledtext',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'spacy.cli',
        'spacy.lang.sr',
        'spacy.lang.en',
        'thinc.api',
        'cymem.cymem',
        'preshed.maps',
        'murmurhash.mrmr',
        'blis',
    ],
    hookspath=[str(Path(__file__).parent)],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'IPython',
        'notebook',
        'jupyter',
        'jupyter_client',
        'jupyter_core',
        'pandas',
        'numpy.testing',
        'PIL',
        'pytest',
        'setuptools',
        'pip',
        'wheel',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

# Process collected files
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# Create executable
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='NEL_Demo',
    debug=False,
    bootloader_ignore_signals=False,
    strip={str(sys.platform != 'win32').lower()},
    upx={str(use_upx).lower()},
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(project_root / 'icon.ico') if (project_root / 'icon.ico').exists() else None,
)

# Collect all files into a directory
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip={str(sys.platform != 'win32').lower()},
    upx={str(use_upx).lower()},
    upx_exclude=[],
    name='NEL_Demo',
)

# For macOS, create an .app bundle
if sys.platform == 'darwin':
    app = BUNDLE(
        coll,
        name='NEL_Demo.app',
        icon=str(project_root / 'icon.icns') if (project_root / 'icon.icns').exists() else None,
        bundle_identifier='rs.tesla.nel-demo',
        info_plist={{
            'CFBundleName': 'NEL Demo',
            'CFBundleDisplayName': 'NEL Demo',
            'CFBundleVersion': '1.0.0',
            'CFBundleShortVersionString': '1.0.0',
            'NSHighResolutionCapable': 'True',
        }},
    )
'''
    
    return spec_content


def main():
    """Main entry point."""
    # Get project root (parent of build_scripts directory)
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    
    # Check for --use-upx flag
    use_upx = '--use-upx' in sys.argv
    
    # Generate spec file
    spec_content = generate_spec_file(project_root, use_upx)
    
    # Write to file
    spec_file = project_root / 'NEL_Demo.spec'
    with open(spec_file, 'w', encoding='utf-8') as f:
        f.write(spec_content)
    
    print(f"Generated PyInstaller spec file: {spec_file}")
    print(f"UPX compression: {'enabled' if use_upx else 'disabled'}")
    print("")
    print("To build using this spec file:")
    print(f"  pyinstaller {spec_file}")


if __name__ == '__main__':
    main()
